//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PurpleAirAPI {

class purpleairapi_basePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="SWIGRegisterExceptionCallbacks_purpleairapi_base")]
    public static extern void SWIGRegisterExceptionCallbacks_purpleairapi_base(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_purpleairapi_base")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_purpleairapi_base(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_purpleairapi_base(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_purpleairapi_base(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="SWIGRegisterStringCallback_purpleairapi_base")]
    public static extern void SWIGRegisterStringCallback_purpleairapi_base(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_purpleairapi_base(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static purpleairapi_basePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirAPIError")]
  public static extern global::System.IntPtr new_PurpleAirAPIError(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirAPIError_what")]
  public static extern string PurpleAirAPIError_what(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirAPIError_get_message")]
  public static extern string PurpleAirAPIError_get_message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete_PurpleAirAPIError")]
  public static extern void delete_PurpleAirAPIError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_StringMap__SWIG_0")]
  public static extern global::System.IntPtr new_StringMap__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_StringMap__SWIG_1")]
  public static extern global::System.IntPtr new_StringMap__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_size")]
  public static extern uint StringMap_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_empty")]
  public static extern bool StringMap_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_Clear")]
  public static extern void StringMap_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_getitem")]
  public static extern string StringMap_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_setitem")]
  public static extern void StringMap_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_ContainsKey")]
  public static extern bool StringMap_ContainsKey(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_Add")]
  public static extern void StringMap_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_Remove")]
  public static extern bool StringMap_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_create_iterator_begin")]
  public static extern global::System.IntPtr StringMap_create_iterator_begin(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_get_next_key")]
  public static extern string StringMap_get_next_key(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_StringMap_destroy_iterator")]
  public static extern void StringMap_destroy_iterator(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.IntPtr jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete_StringMap")]
  public static extern void delete_StringMap(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_debug_log")]
  public static extern void debug_log(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_verify_request_status_codes")]
  public static extern bool verify_request_status_codes(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_convert_text_to_json")]
  public static extern string convert_text_to_json(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_get_request__SWIG_0")]
  public static extern string send_url_get_request__SWIG_0(string jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_get_request__SWIG_1")]
  public static extern string send_url_get_request__SWIG_1(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_get_request__SWIG_2")]
  public static extern string send_url_get_request__SWIG_2(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_get_request__SWIG_3")]
  public static extern string send_url_get_request__SWIG_3(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_post_request")]
  public static extern string send_url_post_request(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_send_url_delete_request")]
  public static extern string send_url_delete_request(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new__string_vector__SWIG_0")]
  public static extern global::System.IntPtr new__string_vector__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new__string_vector__SWIG_1")]
  public static extern global::System.IntPtr new__string_vector__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Clear")]
  public static extern void _string_vector_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Add")]
  public static extern void _string_vector_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_size")]
  public static extern uint _string_vector_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_empty")]
  public static extern bool _string_vector_empty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_capacity")]
  public static extern uint _string_vector_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_reserve")]
  public static extern void _string_vector_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new__string_vector__SWIG_2")]
  public static extern global::System.IntPtr new__string_vector__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_getitemcopy")]
  public static extern string _string_vector_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_getitem")]
  public static extern string _string_vector_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_setitem")]
  public static extern void _string_vector_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_AddRange")]
  public static extern void _string_vector_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_GetRange")]
  public static extern global::System.IntPtr _string_vector_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Insert")]
  public static extern void _string_vector_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_InsertRange")]
  public static extern void _string_vector_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_RemoveAt")]
  public static extern void _string_vector_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_RemoveRange")]
  public static extern void _string_vector_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Repeat")]
  public static extern global::System.IntPtr _string_vector_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Reverse__SWIG_0")]
  public static extern void _string_vector_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Reverse__SWIG_1")]
  public static extern void _string_vector_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_SetRange")]
  public static extern void _string_vector_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Contains")]
  public static extern bool _string_vector_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_IndexOf")]
  public static extern int _string_vector_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_LastIndexOf")]
  public static extern int _string_vector_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI__string_vector_Remove")]
  public static extern bool _string_vector_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete__string_vector")]
  public static extern void delete__string_vector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirReadAPI__SWIG_0")]
  public static extern global::System.IntPtr new_PurpleAirReadAPI__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirReadAPI__SWIG_1")]
  public static extern global::System.IntPtr new_PurpleAirReadAPI__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_data__SWIG_0")]
  public static extern string PurpleAirReadAPI_request_sensor_data__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_data__SWIG_1")]
  public static extern string PurpleAirReadAPI_request_sensor_data__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_data__SWIG_2")]
  public static extern string PurpleAirReadAPI_request_sensor_data__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_0")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7, string jarg8, string jarg9, string jarg10, string jarg11);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_1")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7, string jarg8, string jarg9, string jarg10);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_2")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7, string jarg8, string jarg9);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_3")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7, string jarg8);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_4")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_4(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6, int jarg7);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_5")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5, string jarg6);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_6")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_6(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_7")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_7(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_8")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_8(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_multiple_sensors_data__SWIG_9")]
  public static extern string PurpleAirReadAPI_request_multiple_sensors_data__SWIG_9(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_history__SWIG_0")]
  public static extern string PurpleAirReadAPI_request_sensor_history__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, int jarg4, int jarg5, int jarg6, string jarg7);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_history__SWIG_1")]
  public static extern string PurpleAirReadAPI_request_sensor_history__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, int jarg4, int jarg5, int jarg6);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirReadAPI_request_sensor_history__SWIG_2")]
  public static extern string PurpleAirReadAPI_request_sensor_history__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete_PurpleAirReadAPI")]
  public static extern void delete_PurpleAirReadAPI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirWriteAPI__SWIG_0")]
  public static extern global::System.IntPtr new_PurpleAirWriteAPI__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirWriteAPI__SWIG_1")]
  public static extern global::System.IntPtr new_PurpleAirWriteAPI__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirWriteAPI_post_create_member")]
  public static extern string PurpleAirWriteAPI_post_create_member(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirWriteAPI_delete_member")]
  public static extern string PurpleAirWriteAPI_delete_member(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete_PurpleAirWriteAPI")]
  public static extern void delete_PurpleAirWriteAPI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirLocalAPI__SWIG_0")]
  public static extern global::System.IntPtr new_PurpleAirLocalAPI__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_new_PurpleAirLocalAPI__SWIG_1")]
  public static extern global::System.IntPtr new_PurpleAirLocalAPI__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_PurpleAirLocalAPI_request_local_sensor_data")]
  public static extern string PurpleAirLocalAPI_request_local_sensor_data(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("purpleairapi_base", EntryPoint="CSharp_PurpleAirAPI_delete_PurpleAirLocalAPI")]
  public static extern void delete_PurpleAirLocalAPI(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
