//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PurpleAirAPI {

public class PurpleAirAPIError : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PurpleAirAPIError(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PurpleAirAPIError obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PurpleAirAPIError obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PurpleAirAPIError() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          purpleairapi_basePINVOKE.delete_PurpleAirAPIError(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PurpleAirAPIError(string msg) : this(purpleairapi_basePINVOKE.new_PurpleAirAPIError(msg), true) {
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual string what() {
    string ret = purpleairapi_basePINVOKE.PurpleAirAPIError_what(swigCPtr);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get_message() {
    string ret = purpleairapi_basePINVOKE.PurpleAirAPIError_get_message(swigCPtr);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
