//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PurpleAirAPI {

public class PurpleAirLocalAPI : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PurpleAirLocalAPI(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PurpleAirLocalAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PurpleAirLocalAPI obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PurpleAirLocalAPI() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          purpleairapi_basePINVOKE.delete_PurpleAirLocalAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PurpleAirLocalAPI(_string_vector ipv4_address_list) : this(purpleairapi_basePINVOKE.new_PurpleAirLocalAPI__SWIG_0(_string_vector.getCPtr(ipv4_address_list)), true) {
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public PurpleAirLocalAPI() : this(purpleairapi_basePINVOKE.new_PurpleAirLocalAPI__SWIG_1(), true) {
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public string request_local_sensor_data() {
    string ret = purpleairapi_basePINVOKE.PurpleAirLocalAPI_request_local_sensor_data(swigCPtr);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
