//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PurpleAirAPI {

public class PurpleAirReadAPI : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PurpleAirReadAPI(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PurpleAirReadAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PurpleAirReadAPI obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PurpleAirReadAPI() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          purpleairapi_basePINVOKE.delete_PurpleAirReadAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PurpleAirReadAPI(string api_read_key) : this(purpleairapi_basePINVOKE.new_PurpleAirReadAPI__SWIG_0(api_read_key), true) {
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public PurpleAirReadAPI() : this(purpleairapi_basePINVOKE.new_PurpleAirReadAPI__SWIG_1(), true) {
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public string request_sensor_data(int sensor_index, string read_key, string fields) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_data__SWIG_0(swigCPtr, sensor_index, read_key, fields);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_sensor_data(int sensor_index, string read_key) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_data__SWIG_1(swigCPtr, sensor_index, read_key);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_sensor_data(int sensor_index) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_data__SWIG_2(swigCPtr, sensor_index);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since, int max_age, string nwlng, string nwlat, string selng, string selat) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_0(swigCPtr, fields, location_type, read_keys, show_only, modified_since, max_age, nwlng, nwlat, selng, selat);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since, int max_age, string nwlng, string nwlat, string selng) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_1(swigCPtr, fields, location_type, read_keys, show_only, modified_since, max_age, nwlng, nwlat, selng);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since, int max_age, string nwlng, string nwlat) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_2(swigCPtr, fields, location_type, read_keys, show_only, modified_since, max_age, nwlng, nwlat);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since, int max_age, string nwlng) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_3(swigCPtr, fields, location_type, read_keys, show_only, modified_since, max_age, nwlng);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since, int max_age) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_4(swigCPtr, fields, location_type, read_keys, show_only, modified_since, max_age);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only, string modified_since) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_5(swigCPtr, fields, location_type, read_keys, show_only, modified_since);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys, string show_only) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_6(swigCPtr, fields, location_type, read_keys, show_only);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type, string read_keys) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_7(swigCPtr, fields, location_type, read_keys);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields, string location_type) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_8(swigCPtr, fields, location_type);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_multiple_sensors_data(string fields) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_multiple_sensors_data__SWIG_9(swigCPtr, fields);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_sensor_history(int sensor_index, string read_key, int start_timestamp, int end_timestamp, int average, string fields) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_history__SWIG_0(swigCPtr, sensor_index, read_key, start_timestamp, end_timestamp, average, fields);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_sensor_history(int sensor_index, string read_key, int start_timestamp, int end_timestamp, int average) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_history__SWIG_1(swigCPtr, sensor_index, read_key, start_timestamp, end_timestamp, average);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string request_sensor_history(int sensor_index, string read_key, int start_timestamp, int end_timestamp) {
    string ret = purpleairapi_basePINVOKE.PurpleAirReadAPI_request_sensor_history__SWIG_2(swigCPtr, sensor_index, read_key, start_timestamp, end_timestamp);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
