//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace PurpleAirAPI {

public class purpleairapi_base {
  public static void debug_log(string msg) {
    purpleairapi_basePINVOKE.debug_log(msg);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
  }

  public static bool verify_request_status_codes(int status_code) {
    bool ret = purpleairapi_basePINVOKE.verify_request_status_codes(status_code);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string convert_text_to_json(string text) {
    string ret = purpleairapi_basePINVOKE.convert_text_to_json(text);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_get_request(string request_url, string api_key_to_use, string first_optional_parameter_separator, StringMap optional_parameters_dict) {
    string ret = purpleairapi_basePINVOKE.send_url_get_request__SWIG_0(request_url, api_key_to_use, first_optional_parameter_separator, StringMap.getCPtr(optional_parameters_dict));
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_get_request(string request_url, string api_key_to_use, string first_optional_parameter_separator) {
    string ret = purpleairapi_basePINVOKE.send_url_get_request__SWIG_1(request_url, api_key_to_use, first_optional_parameter_separator);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_get_request(string request_url, string api_key_to_use) {
    string ret = purpleairapi_basePINVOKE.send_url_get_request__SWIG_2(request_url, api_key_to_use);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_get_request(string request_url) {
    string ret = purpleairapi_basePINVOKE.send_url_get_request__SWIG_3(request_url);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_post_request(string request_url, string api_key_to_use, string post_data) {
    string ret = purpleairapi_basePINVOKE.send_url_post_request(request_url, api_key_to_use, post_data);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string send_url_delete_request(string request_url, string api_key_to_use) {
    string ret = purpleairapi_basePINVOKE.send_url_delete_request(request_url, api_key_to_use);
    if (purpleairapi_basePINVOKE.SWIGPendingException.Pending) throw purpleairapi_basePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
