# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _purpleairapi_base
else:
    import _purpleairapi_base

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    r"""Proxy of C++ swig::SwigPyIterator class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _purpleairapi_base.delete_SwigPyIterator

    def value(self):
        r"""value(self) -> PyObject *"""
        return _purpleairapi_base.SwigPyIterator_value(self)

    def incr(self, n=1):
        r"""incr(self, n=1) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        r"""decr(self, n=1) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator_decr(self, n)

    def distance(self, x):
        r"""distance(self, x) -> ptrdiff_t"""
        return _purpleairapi_base.SwigPyIterator_distance(self, x)

    def equal(self, x):
        r"""equal(self, x) -> bool"""
        return _purpleairapi_base.SwigPyIterator_equal(self, x)

    def copy(self):
        r"""copy(self) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator_copy(self)

    def next(self):
        r"""next(self) -> PyObject *"""
        return _purpleairapi_base.SwigPyIterator_next(self)

    def __next__(self):
        r"""__next__(self) -> PyObject *"""
        return _purpleairapi_base.SwigPyIterator___next__(self)

    def previous(self):
        r"""previous(self) -> PyObject *"""
        return _purpleairapi_base.SwigPyIterator_previous(self)

    def advance(self, n):
        r"""advance(self, n) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        r"""__eq__(self, x) -> bool"""
        return _purpleairapi_base.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        r"""__ne__(self, x) -> bool"""
        return _purpleairapi_base.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        r"""__iadd__(self, n) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        r"""__isub__(self, n) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        r"""__add__(self, n) -> SwigPyIterator"""
        return _purpleairapi_base.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        r"""
        __sub__(self, n) -> SwigPyIterator
        __sub__(self, x) -> ptrdiff_t
        """
        return _purpleairapi_base.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _purpleairapi_base:
_purpleairapi_base.SwigPyIterator_swigregister(SwigPyIterator)
class PurpleAirAPIError(object):
    r"""Proxy of C++ PurpleAirAPI::PurpleAirAPIError class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, msg):
        r"""__init__(self, msg) -> PurpleAirAPIError"""
        _purpleairapi_base.PurpleAirAPIError_swiginit(self, _purpleairapi_base.new_PurpleAirAPIError(msg))

    def what(self):
        r"""what(self) -> char const *"""
        return _purpleairapi_base.PurpleAirAPIError_what(self)

    def get_message(self):
        r"""get_message(self) -> std::string"""
        return _purpleairapi_base.PurpleAirAPIError_get_message(self)
    __swig_destroy__ = _purpleairapi_base.delete_PurpleAirAPIError

# Register PurpleAirAPIError in _purpleairapi_base:
_purpleairapi_base.PurpleAirAPIError_swigregister(PurpleAirAPIError)
class StringMap(object):
    r"""Proxy of C++ std::map< std::string,std::string > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        r"""iterator(self) -> SwigPyIterator"""
        return _purpleairapi_base.StringMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        r"""__nonzero__(self) -> bool"""
        return _purpleairapi_base.StringMap___nonzero__(self)

    def __bool__(self):
        r"""__bool__(self) -> bool"""
        return _purpleairapi_base.StringMap___bool__(self)

    def __len__(self):
        r"""__len__(self) -> std::map< std::string,std::string >::size_type"""
        return _purpleairapi_base.StringMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        r"""__getitem__(self, key) -> std::map< std::string,std::string >::mapped_type const &"""
        return _purpleairapi_base.StringMap___getitem__(self, key)

    def __delitem__(self, key):
        r"""__delitem__(self, key)"""
        return _purpleairapi_base.StringMap___delitem__(self, key)

    def has_key(self, key):
        r"""has_key(self, key) -> bool"""
        return _purpleairapi_base.StringMap_has_key(self, key)

    def keys(self):
        r"""keys(self) -> PyObject *"""
        return _purpleairapi_base.StringMap_keys(self)

    def values(self):
        r"""values(self) -> PyObject *"""
        return _purpleairapi_base.StringMap_values(self)

    def items(self):
        r"""items(self) -> PyObject *"""
        return _purpleairapi_base.StringMap_items(self)

    def __contains__(self, key):
        r"""__contains__(self, key) -> bool"""
        return _purpleairapi_base.StringMap___contains__(self, key)

    def key_iterator(self):
        r"""key_iterator(self) -> SwigPyIterator"""
        return _purpleairapi_base.StringMap_key_iterator(self)

    def value_iterator(self):
        r"""value_iterator(self) -> SwigPyIterator"""
        return _purpleairapi_base.StringMap_value_iterator(self)

    def __setitem__(self, *args):
        r"""
        __setitem__(self, key)
        __setitem__(self, key, x)
        """
        return _purpleairapi_base.StringMap___setitem__(self, *args)

    def asdict(self):
        r"""asdict(self) -> PyObject *"""
        return _purpleairapi_base.StringMap_asdict(self)

    def __init__(self, *args):
        r"""
        __init__(self, other) -> StringMap
        __init__(self) -> StringMap
        __init__(self, other) -> StringMap
        """
        _purpleairapi_base.StringMap_swiginit(self, _purpleairapi_base.new_StringMap(*args))

    def empty(self):
        r"""empty(self) -> bool"""
        return _purpleairapi_base.StringMap_empty(self)

    def size(self):
        r"""size(self) -> std::map< std::string,std::string >::size_type"""
        return _purpleairapi_base.StringMap_size(self)

    def swap(self, v):
        r"""swap(self, v)"""
        return _purpleairapi_base.StringMap_swap(self, v)

    def begin(self):
        r"""begin(self) -> std::map< std::string,std::string >::iterator"""
        return _purpleairapi_base.StringMap_begin(self)

    def end(self):
        r"""end(self) -> std::map< std::string,std::string >::iterator"""
        return _purpleairapi_base.StringMap_end(self)

    def rbegin(self):
        r"""rbegin(self) -> std::map< std::string,std::string >::reverse_iterator"""
        return _purpleairapi_base.StringMap_rbegin(self)

    def rend(self):
        r"""rend(self) -> std::map< std::string,std::string >::reverse_iterator"""
        return _purpleairapi_base.StringMap_rend(self)

    def clear(self):
        r"""clear(self)"""
        return _purpleairapi_base.StringMap_clear(self)

    def get_allocator(self):
        r"""get_allocator(self) -> std::map< std::string,std::string >::allocator_type"""
        return _purpleairapi_base.StringMap_get_allocator(self)

    def count(self, x):
        r"""count(self, x) -> std::map< std::string,std::string >::size_type"""
        return _purpleairapi_base.StringMap_count(self, x)

    def erase(self, *args):
        r"""
        erase(self, x) -> std::map< std::string,std::string >::size_type
        erase(self, position)
        erase(self, first, last)
        """
        return _purpleairapi_base.StringMap_erase(self, *args)

    def find(self, x):
        r"""find(self, x) -> std::map< std::string,std::string >::iterator"""
        return _purpleairapi_base.StringMap_find(self, x)

    def lower_bound(self, x):
        r"""lower_bound(self, x) -> std::map< std::string,std::string >::iterator"""
        return _purpleairapi_base.StringMap_lower_bound(self, x)

    def upper_bound(self, x):
        r"""upper_bound(self, x) -> std::map< std::string,std::string >::iterator"""
        return _purpleairapi_base.StringMap_upper_bound(self, x)
    __swig_destroy__ = _purpleairapi_base.delete_StringMap

# Register StringMap in _purpleairapi_base:
_purpleairapi_base.StringMap_swigregister(StringMap)

def debug_log(msg):
    r"""debug_log(msg)"""
    return _purpleairapi_base.debug_log(msg)

def verify_request_status_codes(status_code):
    r"""verify_request_status_codes(status_code) -> bool"""
    return _purpleairapi_base.verify_request_status_codes(status_code)

def convert_text_to_json(text):
    r"""convert_text_to_json(text) -> std::string"""
    return _purpleairapi_base.convert_text_to_json(text)

def send_url_get_request(*args):
    r"""send_url_get_request(request_url, api_key_to_use="", first_optional_parameter_separator="", optional_parameters_dict=std::map< std::string,std::string >()) -> std::string"""
    return _purpleairapi_base.send_url_get_request(*args)

def send_url_post_request(request_url, api_key_to_use, post_data):
    r"""send_url_post_request(request_url, api_key_to_use, post_data) -> std::string"""
    return _purpleairapi_base.send_url_post_request(request_url, api_key_to_use, post_data)

def send_url_delete_request(request_url, api_key_to_use):
    r"""send_url_delete_request(request_url, api_key_to_use) -> std::string"""
    return _purpleairapi_base.send_url_delete_request(request_url, api_key_to_use)
class _string_vector(object):
    r"""Proxy of C++ std::vector< std::string > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self) -> "swig::SwigPyIterator *":
        r"""iterator(self) -> SwigPyIterator"""
        return _purpleairapi_base._string_vector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self) -> "bool":
        r"""__nonzero__(self) -> bool"""
        return _purpleairapi_base._string_vector___nonzero__(self)

    def __bool__(self) -> "bool":
        r"""__bool__(self) -> bool"""
        return _purpleairapi_base._string_vector___bool__(self)

    def __len__(self) -> "std::vector< std::string >::size_type":
        r"""__len__(self) -> std::vector< std::string >::size_type"""
        return _purpleairapi_base._string_vector___len__(self)

    def __getslice__(self, i: "std::vector< std::string >::difference_type", j: "std::vector< std::string >::difference_type") -> "std::vector< std::string,std::allocator< std::string > > *":
        r"""__getslice__(self, i, j) -> _string_vector"""
        return _purpleairapi_base._string_vector___getslice__(self, i, j)

    def __setslice__(self, *args) -> "void":
        r"""
        __setslice__(self, i, j)
        __setslice__(self, i, j, v)
        """
        return _purpleairapi_base._string_vector___setslice__(self, *args)

    def __delslice__(self, i: "std::vector< std::string >::difference_type", j: "std::vector< std::string >::difference_type") -> "void":
        r"""__delslice__(self, i, j)"""
        return _purpleairapi_base._string_vector___delslice__(self, i, j)

    def __delitem__(self, *args) -> "void":
        r"""
        __delitem__(self, i)
        __delitem__(self, slice)
        """
        return _purpleairapi_base._string_vector___delitem__(self, *args)

    def __getitem__(self, *args) -> "std::vector< std::string >::value_type const &":
        r"""
        __getitem__(self, slice) -> _string_vector
        __getitem__(self, i) -> std::vector< std::string >::value_type const &
        """
        return _purpleairapi_base._string_vector___getitem__(self, *args)

    def __setitem__(self, *args) -> "void":
        r"""
        __setitem__(self, slice, v)
        __setitem__(self, slice)
        __setitem__(self, i, x)
        """
        return _purpleairapi_base._string_vector___setitem__(self, *args)

    def pop(self) -> "std::vector< std::string >::value_type":
        r"""pop(self) -> std::vector< std::string >::value_type"""
        return _purpleairapi_base._string_vector_pop(self)

    def append(self, x: "std::vector< std::string >::value_type const &") -> "void":
        r"""append(self, x)"""
        return _purpleairapi_base._string_vector_append(self, x)

    def empty(self) -> "bool":
        r"""empty(self) -> bool"""
        return _purpleairapi_base._string_vector_empty(self)

    def size(self) -> "std::vector< std::string >::size_type":
        r"""size(self) -> std::vector< std::string >::size_type"""
        return _purpleairapi_base._string_vector_size(self)

    def swap(self, v: "_string_vector") -> "void":
        r"""swap(self, v)"""
        return _purpleairapi_base._string_vector_swap(self, v)

    def begin(self) -> "std::vector< std::string >::iterator":
        r"""begin(self) -> std::vector< std::string >::iterator"""
        return _purpleairapi_base._string_vector_begin(self)

    def end(self) -> "std::vector< std::string >::iterator":
        r"""end(self) -> std::vector< std::string >::iterator"""
        return _purpleairapi_base._string_vector_end(self)

    def rbegin(self) -> "std::vector< std::string >::reverse_iterator":
        r"""rbegin(self) -> std::vector< std::string >::reverse_iterator"""
        return _purpleairapi_base._string_vector_rbegin(self)

    def rend(self) -> "std::vector< std::string >::reverse_iterator":
        r"""rend(self) -> std::vector< std::string >::reverse_iterator"""
        return _purpleairapi_base._string_vector_rend(self)

    def clear(self) -> "void":
        r"""clear(self)"""
        return _purpleairapi_base._string_vector_clear(self)

    def get_allocator(self) -> "std::vector< std::string >::allocator_type":
        r"""get_allocator(self) -> std::vector< std::string >::allocator_type"""
        return _purpleairapi_base._string_vector_get_allocator(self)

    def pop_back(self) -> "void":
        r"""pop_back(self)"""
        return _purpleairapi_base._string_vector_pop_back(self)

    def erase(self, *args) -> "std::vector< std::string >::iterator":
        r"""
        erase(self, pos) -> std::vector< std::string >::iterator
        erase(self, first, last) -> std::vector< std::string >::iterator
        """
        return _purpleairapi_base._string_vector_erase(self, *args)

    def __init__(self, *args):
        r"""
        __init__(self) -> _string_vector
        __init__(self, other) -> _string_vector
        __init__(self, size) -> _string_vector
        __init__(self, size, value) -> _string_vector
        """
        _purpleairapi_base._string_vector_swiginit(self, _purpleairapi_base.new__string_vector(*args))

    def push_back(self, x: "std::vector< std::string >::value_type const &") -> "void":
        r"""push_back(self, x)"""
        return _purpleairapi_base._string_vector_push_back(self, x)

    def front(self) -> "std::vector< std::string >::value_type const &":
        r"""front(self) -> std::vector< std::string >::value_type const &"""
        return _purpleairapi_base._string_vector_front(self)

    def back(self) -> "std::vector< std::string >::value_type const &":
        r"""back(self) -> std::vector< std::string >::value_type const &"""
        return _purpleairapi_base._string_vector_back(self)

    def assign(self, n: "std::vector< std::string >::size_type", x: "std::vector< std::string >::value_type const &") -> "void":
        r"""assign(self, n, x)"""
        return _purpleairapi_base._string_vector_assign(self, n, x)

    def resize(self, *args) -> "void":
        r"""
        resize(self, new_size)
        resize(self, new_size, x)
        """
        return _purpleairapi_base._string_vector_resize(self, *args)

    def insert(self, *args) -> "void":
        r"""
        insert(self, pos, x) -> std::vector< std::string >::iterator
        insert(self, pos, n, x)
        """
        return _purpleairapi_base._string_vector_insert(self, *args)

    def reserve(self, n: "std::vector< std::string >::size_type") -> "void":
        r"""reserve(self, n)"""
        return _purpleairapi_base._string_vector_reserve(self, n)

    def capacity(self) -> "std::vector< std::string >::size_type":
        r"""capacity(self) -> std::vector< std::string >::size_type"""
        return _purpleairapi_base._string_vector_capacity(self)
    __swig_destroy__ = _purpleairapi_base.delete__string_vector

# Register _string_vector in _purpleairapi_base:
_purpleairapi_base._string_vector_swigregister(_string_vector)
class PurpleAirReadAPI(object):
    r"""Proxy of C++ PurpleAirAPI::PurpleAirReadAPI class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(self, api_read_key="") -> PurpleAirReadAPI"""
        _purpleairapi_base.PurpleAirReadAPI_swiginit(self, _purpleairapi_base.new_PurpleAirReadAPI(*args, **kwargs))

    def request_sensor_data(self, *args, **kwargs) -> "std::string":
        r"""request_sensor_data(self, sensor_index, read_key="", fields="") -> std::string"""
        return _purpleairapi_base.PurpleAirReadAPI_request_sensor_data(self, *args, **kwargs)

    def request_multiple_sensors_data(self, *args, **kwargs) -> "std::string":
        r"""request_multiple_sensors_data(self, fields, location_type="", read_keys="", show_only="", modified_since="", max_age=0, nwlng="", nwlat="", selng="", selat="") -> std::string"""
        return _purpleairapi_base.PurpleAirReadAPI_request_multiple_sensors_data(self, *args, **kwargs)

    def request_sensor_history(self, *args, **kwargs) -> "std::string":
        r"""request_sensor_history(self, sensor_index, read_key, start_timestamp, end_timestamp, average=0, fields="") -> std::string"""
        return _purpleairapi_base.PurpleAirReadAPI_request_sensor_history(self, *args, **kwargs)
    __swig_destroy__ = _purpleairapi_base.delete_PurpleAirReadAPI

# Register PurpleAirReadAPI in _purpleairapi_base:
_purpleairapi_base.PurpleAirReadAPI_swigregister(PurpleAirReadAPI)
class PurpleAirWriteAPI(object):
    r"""Proxy of C++ PurpleAirAPI::PurpleAirWriteAPI class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(self, api_write_key="") -> PurpleAirWriteAPI"""
        _purpleairapi_base.PurpleAirWriteAPI_swiginit(self, _purpleairapi_base.new_PurpleAirWriteAPI(*args, **kwargs))

    def post_create_member(self, sensor_index: "int") -> "std::string":
        r"""post_create_member(self, sensor_index) -> std::string"""
        return _purpleairapi_base.PurpleAirWriteAPI_post_create_member(self, sensor_index)

    def delete_member(self, member_id: "int") -> "std::string":
        r"""delete_member(self, member_id) -> std::string"""
        return _purpleairapi_base.PurpleAirWriteAPI_delete_member(self, member_id)
    __swig_destroy__ = _purpleairapi_base.delete_PurpleAirWriteAPI

# Register PurpleAirWriteAPI in _purpleairapi_base:
_purpleairapi_base.PurpleAirWriteAPI_swigregister(PurpleAirWriteAPI)
class PurpleAirLocalAPI(object):
    r"""Proxy of C++ PurpleAirAPI::PurpleAirLocalAPI class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args, **kwargs):
        r"""__init__(self, ipv4_address_list=std::vector< std::string >()) -> PurpleAirLocalAPI"""
        _purpleairapi_base.PurpleAirLocalAPI_swiginit(self, _purpleairapi_base.new_PurpleAirLocalAPI(*args, **kwargs))

    def request_local_sensor_data(self) -> "std::string":
        r"""request_local_sensor_data(self) -> std::string"""
        return _purpleairapi_base.PurpleAirLocalAPI_request_local_sensor_data(self)
    __swig_destroy__ = _purpleairapi_base.delete_PurpleAirLocalAPI

# Register PurpleAirLocalAPI in _purpleairapi_base:
_purpleairapi_base.PurpleAirLocalAPI_swigregister(PurpleAirLocalAPI)

